app/build.gradle.kts

This change sets the `sonar.projectKey`, `sonar.projectName`, and `sonar.organization` properties of `app/build.gradle.kts` with the values provided by Sonar, for it to work properly in the CI.

ci(gradle): Change the Sonar credentials to match the project.

---

README.md

This updates the README of the project with the description that was submitted to the coaches on Moodle. The description is subject to change as the project evolves during the semester.

Update README.md with project description.

---

app/src/androidTest/java/com/android/unio/ui/ExploreScreenTest.kt
app/src/main/java/com/android/unio/model/association/MockAssociations.kt
app/src/main/java/com/android/unio/ui/explore/Explore.kt

Things that still need to be implemented:

feat(explore): implement base of the explore screen

---

app/src/main/java/com/android/unio/model/association/AssociationRepository.kt
app/src/main/java/com/android/unio/model/association/AssociationRepositoryFirestore.kt
app/src/main/java/com/android/unio/model/association/ExploreViewModel.kt
app/src/test/java/com/android/unio/model/association/ExploreViewModelTest.kt

The explore view model will enable us to get the list of associations from the firebase database. This will be useful for screens such as the explore screen, which will display all associations, sorted vertically by category, and horizontally by some other logic (or none).

chore(model/association): Create view model for the association database.

---

app/src/main/java/com/android/unio/ui/explore/Explore.kt

This is simply to show, during the S1 demo, that we can scroll vertically through the association categories.
The height increase will allow the lazy list to have enough height such that we have to scroll so see the last category.

chore(explore): change height of association item for demo

---

app/src/main/java/com/android/unio/model/association/AssociationRepositoryFirestore.kt

This update enhances the quality of our code:
- It can still handles the simple functions like `addAssociation`, `updateAssociation` and `deleteAssociation`, that use a simple `() -> Unit` typed `onSuccess` function.
- It now supports functions where their `onSuccess` function might require a different input type. This includes the `getAssociations` and `getAssociationWithId` functions.

chore(association): refactor association repository with universal function

---

app/src/main/java/com/android/unio/model/image/ImageRepository.kt
app/src/main/java/com/android/unio/model/image/ImageRepositoryFirebaseStorage.kt
app/src/test/java/com/android/unio/model/image/ImageRepositoryFirebaseStorageTest.kt

Fix uploadImage so it outputs the image's download link automatically.
Set the getDownloadUrl as private because it shouldn't be used elsewhere in the project.
Also added some comments to the methods.

fix(model/image): upload image

---

app/src/androidTest/java/com/android/unio/ui/explore/ExploreScreenTest.kt
app/src/main/java/com/android/unio/ui/explore/Explore.kt

The goal of this small PR is simply to increase code coverage and have more edge cases, to make the testing more robust.
- A new test `testClickOnAssociation` has been added. It performs a click on the association item (with its personalized tag), and checks that the navigation is correct, Navigation parameter included. This is done for all associations on the screen, with the mock list `associations` present in the ExploreScreenTest file.

test(explore): add tests to increase code coverage of Explore.kt

---

.github/workflows/apk-maker.yml
app/src/androidTest/java/com/android/unio/ui/association/AssociationProfileTest.kt
app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt

The line coverage of the "AssociationProfile" can be improved with more tests. This is the purpose of this PR. It includes :
- Test the different button if they do the the correct behavior
- To do so, we change the placeholder action "Toast.show" with another one that is easier to test. We use instead "SnackBar".
More test will be done when we will link the backend to this screen

test: Write additional tests to increase code coverage for AssociationProfile

---

.github/workflows/apk-maker.yml

To be able to download the apk of the app directly from GitHub, a workflow is needed to be setup. This is the purpose of this PR. It includes : 
- A apk-maker.yml file that will be useful to setup the Workflow

chore(action/apk-maker): add a yml file that should make apk of the main automatically

---

app/src/main/java/com/android/unio/ui/explore/Explore.kt

This PR restores the placeholder image for the Explore screen to demonstrate the intended behavior of the screen with visible content for the upcoming demo and milestone. While previous efforts were made to implement image URLs for associations, we decided to revert to the placeholder image to better demonstrate the behavior of the screen, instead of having to show, for the milestone 1, empty images slots. The placeholder will be replaced with actual images when all urls work in a future update.

fix(explore): restore placeholder image for demo to display associations visually

---

app/src/androidTest/java/com/android/unio/ui/user/UserProfileTest.kt
app/src/main/java/com/android/unio/MainActivity.kt
app/src/main/java/com/android/unio/model/firestore/transform/Hydration.kt
app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
app/src/main/java/com/android/unio/model/user/User.kt
app/src/main/java/com/android/unio/ui/authentication/AccountDetails.kt
app/src/test/java/com/android/unio/model/firestore/HydrationAndSerializationTest.kt
app/src/test/java/com/android/unio/model/user/UserRepositoryFirestoreTest.kt
app/src/test/java/com/android/unio/model/user/UserTest.kt
app/src/test/java/com/android/unio/model/user/UserViewModelTest.kt

Small PR that refactors the user data class as we've noticed the the `hasProvidedAccountDetails` boolean attribute is completely redundant. We can instead use any other required field such as `FirstName` or `LastName` to check that the user has indeed filled out his `AccountDetails`. This ensures that the navigation still works properly.
This PR includes : 
- Changed User data class.
- All the subsequent modifications for tests and other methods.

Refactor User data class - Remove pointless attribute 

---

app/src/androidTest/java/com/android/unio/screen/EventListOverviewTest.kt
app/src/androidTest/java/com/android/unio/ui/BottomNavigationTest.kt
app/src/androidTest/java/com/android/unio/ui/ScreenDisplayingTest.kt
app/src/main/java/com/android/unio/MainActivity.kt
app/src/main/java/com/android/unio/model/search/SearchViewModel.kt
app/src/main/java/com/android/unio/ui/explore/Explore.kt
app/src/main/java/com/android/unio/ui/home/Home.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

This PR changes the Home screen and adds a search bar which allows the user to search for a specific event by keyword. It is quite similar in how it works to the Search front end for the explore associations page, but displays the events found as EventCard instead of list items like in the Associations. I've also refactored the SearchViewModel's searchDebounced function to allow it to work for events and associations, and potentially any other type of document we'd like to search on.

Connect event frontend to the search backend

---

app/src/androidTest/java/com/android/unio/ui/ScreenDisplayingTest.kt
app/src/androidTest/java/com/android/unio/ui/association/AssociationProfileTest.kt
app/src/androidTest/java/com/android/unio/ui/explore/ExploreScreenTest.kt
app/src/androidTest/java/com/android/unio/ui/user/UserProfileTest.kt
app/src/main/java/com/android/unio/MainActivity.kt
app/src/main/java/com/android/unio/mocks/association/MockAssociation.kt
app/src/main/java/com/android/unio/model/association/Association.kt
app/src/main/java/com/android/unio/model/association/AssociationViewModel.kt
app/src/main/java/com/android/unio/model/authentication/AuthViewModel.kt
app/src/main/java/com/android/unio/model/firestore/ReferenceList.kt
app/src/main/java/com/android/unio/model/firestore/transform/Hydration.kt
app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
app/src/main/java/com/android/unio/model/user/UserViewModel.kt
app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
app/src/main/java/com/android/unio/ui/event/EventDetails.kt
app/src/main/java/com/android/unio/ui/explore/Explore.kt
app/src/main/java/com/android/unio/ui/navigation/NavigationAction.kt
app/src/main/java/com/android/unio/ui/user/UserProfile.kt
app/src/test/java/com/android/unio/model/association/AssociationRepositoryFirestoreTest.kt
app/src/test/java/com/android/unio/model/firestore/HydrationAndSerializationTest.kt
app/src/test/java/com/android/unio/model/search/SearchRepositoryTest.kt
app/src/test/java/com/android/unio/ui/NavigationActionTest.kt

The main objective of this pull request is to fix an issue that came with #104, where a backend request was made directly from a Composable's scope in `AssociationProfile`, which thus made Firestore requests at every composable refresh.
This issue is now fixed, along with a refactor of the `AssociationViewModel`. To keep consistency accross the project, the same refactor was reflected in in `UserProfile`.
The most notable change of the refactor is to remove the use of the string parameter `{uid}` of the association profile route. Instead, the association is stored in the `AssociationViewModel`. This was decided after discussing with @armouldr, who is currently implementing the same process for the `EventDetails`.

Refactor Association Profile and several other fixes

---

app/src/androidTest/java/com/android/unio/ui/home/HomeTest.kt
app/src/main/java/com/android/unio/model/strings/test_tags/HomeTestTags.kt
app/src/main/java/com/android/unio/ui/home/Home.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

The top bar menu was previously hardcoded a looked a bit "drafty" so I refactored it. It now uses the TabRow composable. I chose to use a custom indicator lambda so that the indicator moves along with the user's scroll instead of moving after the scroll.
This change took me way too much time but it looks cool ;)
I also cut the Home screen into smaller composables to make it more readable.

Feat/Home: Change Home page top bar menu

---

app/build.gradle.kts
app/src/androidTest/java/com/android/unio/end2end/EndToEndTest.kt

This pull request adds some minor utilities that aim to help running end-to-end tests locally. These are only helpful tools for developers and are not meant to be included in the CI. There are two Gradle commands that have been added:
- `startFirebaseEmulators` Simply starts the Firebase emulators as defined by `firebase.json` and imports the data stored in `firebase/emulator-data`.
- `connectedCheckWithFirebaseEmulators` Same as above, but also runs `connectedCheck` when the emulators are launched and closes the emulators after the tests are executed.
Note that I have only tested these Gradle commands on Windows as I only have a Windows PC. Please let me know if they do not work on Linux or MacOS.
This pull request also cleans up a little the `EndToEndTest` class, with better error …

Minor end-to-end testing utilities

---

app/src/androidTest/java/com/android/unio/ui/ScreenDisplayingTest.kt
app/src/androidTest/java/com/android/unio/ui/authentication/AccountDetailsTest.kt
app/src/androidTest/java/com/android/unio/ui/event/EventDetailsTest.kt
app/src/main/java/com/android/unio/MainActivity.kt
app/src/main/java/com/android/unio/model/map/MapViewModel.kt
app/src/main/java/com/android/unio/ui/event/EventDetails.kt
app/src/main/java/com/android/unio/ui/home/Home.kt
app/src/main/java/com/android/unio/ui/map/Map.kt
app/src/test/java/com/android/unio/model/map/MapViewModelTest.kt

Link the map button in EventDetails to the map screen, such that the map is centered to the event in question.
For that I need to :
-> add a centerLocation stateflow in MapViewModel
-> add a setCenterLocation method in MapViewModel
-> modify the map screen accordingly
How it works:
in Home: simply navigate to Map without specifying any location, this will focus on userLocation
in EventDetails : use setCenterLocation method to

Link EventDetails to the Map Screen

---

app/src/main/java/com/android/unio/ui/home/Home.kt

There is a bug with the Top bar navigation that makes the Screen display 2 times the same screen during the scroll. I fixed it by using HorizontalPager correctly (using its page value-parameter instead of pagerState.currentPage).

Fix: Home page navigation

---

app/src/androidTest/java/com/android/unio/components/association/AssociationProfileTest.kt
app/src/main/java/com/android/unio/model/follow/ConcurrentAssociationUserRepositoryFirestore.kt
app/src/main/java/com/android/unio/model/utils/Utils.kt
app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
app/src/main/java/com/android/unio/ui/authentication/Welcome.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

There are multiple feature that do not work in offline mode. The "following" feature is one of them.
The user has to leave the screen and come back for the button to be clickable again, and the follow count isn't increased.
When you follow an association, two repositories are essentially called in ConcurrentAssociationUserRepositoryFirestore, which runs the calls in a runBatch.
I suspect this batch operation is the issue, and has to be handled differently to work with offline mode, or another operation should be done after to fix the bug.

Adapt the "following" feature to work in offline mode

---

app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
app/src/main/java/com/android/unio/model/search/SearchRepository.kt
app/src/test/java/com/android/unio/model/search/SearchRepositoryTest.kt

Another issue is encountered with the application. When first searching for an event or a association, or more generally, when we use the searchViewModel, and then we try to follow/save an event, an unexpected crash happens.
This is the error message the we get in the log cat :
```
Process: com.android.unio, PID: 26561
java.lang.IllegalStateException: Already resumed
at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
at com.android.unio.model.search.SearchRepository$eventDocumentToEvent$2$1.invoke(SearchRepository.kt:216)
at com.android.unio.model.search.SearchRepository$eventDocumentToEvent$2$1.invoke(SearchRepository.kt:214)
at com.android.unio.model.event.EventRepositoryFirestore.getEventWithId$lambda$1(EventRepositoryFirestore.kt:65)
at …
```

Application crashes if we search then follow/save an event

---

app/src/androidTest/java/com/android/unio/components/user/UserClaimAssociationTest.kt
app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
app/src/main/java/com/android/unio/ui/user/UserClaimAssociation.kt
app/src/main/java/com/android/unio/ui/user/UserClaimAssociationPresidentialRights.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/android/unio/model/firestore/HydrationAndSerializationTest.kt

From #269. Some components in the "Claim Association" page behave not like expected. This task aims to correct this. Precisely, this means :
- The three dots top right do not do anything, and should be removed
- The search bar should be enabled by default, as it makes no sense for it to be toggled off. Or if for some reason it does make sense the logic for it should be implemented
- Create association" is currently unimplemented and should be removed

Rework Claim Association

---

app/src/main/java/com/android/unio/ui/components/EventEditComponents.kt
app/src/main/java/com/android/unio/ui/event/EventCreation.kt
app/src/main/java/com/android/unio/ui/event/EventEdit.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

This issue was flagged https://github.com/SwEnt-Group13/Unio/issues/269. It is part of polishing the inconsistencies of our app. In event creation/edition, you cannot save your work if some inputs are not filled out, but currently, it is not shown which input is missing. This task aims solve this issue

Add highlighting to missing inputs in Event creation and Event edition
